# Generated by Django 4.2.7 on 2026-02-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_intolerant_of_glucose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intolerant_of_glucose',
            field=models.BooleanField(null=True, verbose_name='Непереносит глюкозу'),
        ),
        migrations.AlterField(
            model_name='user',
            name='intolerant_of_lactose',
            field=models.BooleanField(null=True, verbose_name='Непереносит лактозу'),
        ),
        migrations.AlterField(
            model_name='user',
            name='intolerant_of_sugar',
            field=models.BooleanField(null=True, verbose_name='Непереносит сахару'),
        ),
        migrations.AlterField(
            model_name='user',
            name='intolerant_of_vegetarian',
            field=models.BooleanField(null=True, verbose_name='Предпочитает вегетарианское'),
        ),
    ]
