# Generated by Django 4.2.7 on 2026-02-08 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('units_of_measurement', models.CharField(max_length=150, verbose_name='Еденицы измерения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'products',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='Название продукта')),
                ('product_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество продукта')),
                ('units_of_measurement', models.CharField(max_length=150, verbose_name='Еденицы измерения')),
                ('status', models.BooleanField(default=False, verbose_name='Статус (принято)')),
                ('rejected', models.BooleanField(default=False, verbose_name='Отклонено')),
            ],
            options={
                'verbose_name': 'Заявка на покупку',
                'verbose_name_plural': 'Заявки на покупку',
                'db_table': 'purchase_requests',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DishesServed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=150, verbose_name='Блюдо')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выданное блюдо',
                'verbose_name_plural': 'выданные блюда',
                'db_table': 'dishes_served',
                'ordering': ('id',),
            },
        ),
    ]
