# Generated by Django 4.2.7 on 2026-02-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='Название продукта')),
                ('product_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество продукта')),
                ('units_of_measurement', models.CharField(verbose_name='Еденицы измерения')),
                ('status', models.BooleanField(default=False, verbose_name='Статус (принято)')),
            ],
            options={
                'verbose_name': 'Заявка на покупку',
                'verbose_name_plural': 'Заявки на покупку',
                'db_table': 'purchase_requests',
                'ordering': ('id',),
            },
        ),
    ]
