# Generated by Django 4.2.7 on 2026-02-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0002_purchaserequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequests',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Отклонено'),
        ),
    ]
