# Generated by Django 4.2.7 on 2026-02-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('food_intake', models.CharField(max_length=150, verbose_name='Приём пищи')),
                ('is_glucose', models.BooleanField(verbose_name='Есть глюкоза')),
                ('is_lactose', models.BooleanField(verbose_name='Есть лактоза')),
                ('is_sugar', models.BooleanField(verbose_name='Есть сахара')),
                ('is_vegetarian', models.BooleanField(verbose_name='Вегетарианское')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'db_table': 'dishes',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=150, unique=True, verbose_name='Название блюда')),
                ('estimation', models.CharField(max_length=150, unique=True, verbose_name='Оценка')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
                'ordering': ('id',),
            },
        ),
    ]
