# Generated by Django 4.2.7 on 2026-02-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedmeals',
            name='paid_for',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Заплачено ₽'),
        ),
    ]
