# Generated by Django 4.2.7 on 2026-02-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='composition',
            field=models.TextField(null=True, verbose_name='Состав'),
        ),
    ]
