# Generated by Django 4.2.7 on 2026-02-07 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedMeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(verbose_name='Ключ')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.dishes', verbose_name='Блюдо')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Купленное блюдо',
                'verbose_name_plural': 'Купленные блюда',
                'db_table': 'purchased_meals',
                'ordering': ('id',),
            },
        ),
    ]
